### ISSUE TITLE
Heroimage broken

### ISSUE THREAD

**Issue by janstieler** [floccusaddon/website#2]
Hi,
on Chrome Version 116.0.5845.187 (Offizieller Build) (x86_64) on a Mac the heroimage with the monitor and mobile phone is too big.
![Bildschirmfoto 2023-12-30 um 18 08 23](https://github.com/floccusaddon/website/assets/754880/bfdd5e6d-9657-430e-9623-29f284ed9ced)

**Comment by marcelklehr** [comment]
fixed by https://github.com/floccusaddon/nuxt-website/commit/34d45c0c8572a360e4c338edb7bc63f5ddb32850
